import { JobOrder } from "@/types/order.type";

export const MOCK_ORDERS: JobOrder[] = [
  {
    id: "1",
    title: "TUYỂN 5 NỮ ĐI NHẬT - LÀM LINH KIỆN Ô TÔ (GUNMA, NAGANO)",
    image: "https://picsum.photos/600/400?job1",
    salary: "Lương cơ bản: ~188,907 Yên/tháng",
    date: "03/04/2026",
    location: "Nagano và Gunma (Được chọn tỉnh)",
    age: "Nữ 18-30 tuổi",
    description:
      "TUYỂN 5 NỮ ĐI NHẬT – LÀM LINH KIỆN Ô TÔ (NAGANO). Tuổi: 18-30, tốt nghiệp THPT, sức khỏe tốt, không hình xăm. Công việc: sản xuất linh kiện ô tô, làm theo ca (có tăng ca). Phỏng vấn: 03/04/2026 | Dự kiến xuất cảnh: 09/2026",
    content: "Nội dung đơn hàng",
    category: "Linh kiện ô tô",
    country: "Nhật Bản",
    gender: "female",
  },
  {
    id: "2",
    title: "NỮ CHẾ BIẾN THỰC PHẨM KANTO - PHÍ 120TR",
    image: "https://picsum.photos/600/400?job2",
    salary: "Lương ~197,600 Yên/tháng",
    date: "07/04/2026",
    location: "Chiba - Ibaraki (Nhật Bản)",
    age: "18-30",
    description:
      "NỮ CHẾ BIẾN THỰC PHẨM KANTO – PHÍ 120TR. Tuyển 35 nữ, tuổi 18-30, tốt nghiệp THPT. Công việc: chế biến thực phẩm. Lương ~197,600 Yên/tháng. Phỏng vấn 04/2026 – xuất cảnh 10/2026",
    content: "Nội dung đơn hàng",
    category: "Chế biến thực phẩm",
    country: "Nhật Bản",
    gender: "female",
  },
  {
    id: "3",
    title: "BAO ĐỖ - NAM BẢO DƯỠNG Ô TÔ KAGAWA (YÊU CẦU KINH NGHIỆM)",
    image: "https://picsum.photos/600/400?job3",
    salary: "Lương ~180,000 Yên/tháng",
    date: "03/04/2026",
    location: "Kagawa",
    age: "18-35",
    description:
      "BAO ĐỖ – NAM BẢO DƯỠNG Ô TÔ KAGAWA (YÊU CẦU KINH NGHIỆM). Nam 18-35 tuổi, sửa chữa - bảo dưỡng ô tô, cần có tay nghề. Lương ~180,000 yên/tháng, senpai thực lĩnh 18-20 man. Xuất cảnh 4-6 tháng. Tiền cử gặp mặt - bao đỗ",
    content: "Nội dung đơn hàng",
    category: "Bảo dưỡng ô tô",
    country: "Nhật Bản",
    gender: "male",
  },
  {
    id: "4",
    title: "NAM CÔNG XƯỞNG LƯƠNG CAO – CTY HỖ TRỢ 2 MAN TIỀN NHÀ",
    image: "https://picsum.photos/600/400?job4",
    salary: "Lương 1.045 yên/giờ",
    date: "03/04/2026",
    location: "Wakayama, Nhật Bản",
    age: "Nam: 20-28",
    description:
      "NAM CÔNG XƯỞNG LƯƠNG CAO – CTY HỖ TRỢ 2 MAN TIỀN NHÀ. Làm việc tại Wakayama, Nhật Bản – đóng gói sản phẩm nhựa. Lương 1.045 yên/giờ, nhiều cơ hội tăng ca thu nhập tốt. Hỗ trợ 2 man tiền nhà, có sẵn TTS người Việt",
    content: "Nội dung đơn hàng",
    category: "Công xưởng",
    country: "Nhật Bản",
    gender: "male",
  },
  {
    id: "5",
    title: "NAM ĐÓNG GÓI CÔNG NGHIỆP – MIE (NHẬT BẢN)",
    image: "https://picsum.photos/600/400?job5",
    salary: "Lương cơ bản: ~185,000 yên/tháng",
    date: "27/03/2026",
    location: "Mie",
    age: "20-30",
    description:
      "Nam đóng gói công nghiệp – Mie (Nhật Bản). Công việc: Đóng gói công nghiệp, môi trường ổn định – có senpai người Việt hỗ trợ. Lương cơ bản: ~185,000 yên/tháng (chưa tính làm thêm), nhiều việc tăng ca. Thi tuyển: 27/03/2026 – bay sau 4-6 tháng",
    content: "Nội dung đơn hàng",
    category: "Đóng gói",
    country: "Nhật Bản",
    gender: "male",
  },
  {
    id: "6",
    title: "TUYỂN 3 NAM ĐI NHẬT – IBARAKI (ĐÓNG GÓI CÔNG NGHIỆP)",
    image: "https://picsum.photos/600/400?job6",
    salary: "Lương cơ bản: ~179,000 yên/tháng",
    date: "03/04/2026",
    location: "Tỉnh Ibaraki - Nhật Bản",
    age: "18-32",
    description:
      "TUYỂN 3 NAM ĐI NHẬT – IBARAKI (ĐÓNG GÓI CÔNG NGHIỆP). Công việc: sản xuất, đóng gói thảm, tấm trải sàn. Lương cơ bản: ~179,000 yên/tháng (chưa tính tăng ca). Lịch phỏng vấn: 03/04/2026 – cần form gấp",
    content: "Nội dung đơn hàng",
    category: "Đóng gói",
    country: "Nhật Bản",
    gender: "male",
  },
];
